package com.singulee.carschool.pojo;

import java.sql.Date;

public class Student{
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.stuId
     *
     * @mbg.generated
     */
    private Integer stuid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.stuName
     *
     * @mbg.generated
     */
    private String stuname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.stuPhone
     *
     * @mbg.generated
     */
    private String stuphone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.stuPwd
     *
     * @mbg.generated
     */
    private String stupwd;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.stuStust
     *
     * @mbg.generated
     */
    private String stustust;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.stuSta
     *
     * @mbg.generated
     */
    private Integer stusta;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.stuStartDate
     *
     * @mbg.generated
     */
    private Date stustartdate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.stuEndDate
     *
     * @mbg.generated
     */
    private Date stuenddate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.teaId
     *
     * @mbg.generated
     */
    private Integer teaid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.stuBirth
     *
     * @mbg.generated
     */
    private Date stubirth;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.stuSex
     *
     * @mbg.generated
     */
    private Integer stusex;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.stuImg
     *
     * @mbg.generated
     */
    private String stuimg;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.extend1
     *
     * @mbg.generated
     */
    private String extend1;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.extend2
     *
     * @mbg.generated
     */
    private String extend2;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.stuId
     *
     * @return the value of student.stuId
     *
     * @mbg.generated
     */
    public Integer getStuid() {
        return stuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.stuId
     *
     * @param stuid the value for student.stuId
     *
     * @mbg.generated
     */
    public void setStuid(Integer stuid) {
        this.stuid = stuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.stuName
     *
     * @return the value of student.stuName
     *
     * @mbg.generated
     */
    public String getStuname() {
        return stuname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.stuName
     *
     * @param stuname the value for student.stuName
     *
     * @mbg.generated
     */
    public void setStuname(String stuname) {
        this.stuname = stuname == null ? null : stuname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.stuPhone
     *
     * @return the value of student.stuPhone
     *
     * @mbg.generated
     */
    public String getStuphone() {
        return stuphone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.stuPhone
     *
     * @param stuphone the value for student.stuPhone
     *
     * @mbg.generated
     */
    public void setStuphone(String stuphone) {
        this.stuphone = stuphone == null ? null : stuphone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.stuPwd
     *
     * @return the value of student.stuPwd
     *
     * @mbg.generated
     */
    public String getStupwd() {
        return stupwd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.stuPwd
     *
     * @param stupwd the value for student.stuPwd
     *
     * @mbg.generated
     */
    public void setStupwd(String stupwd) {
        this.stupwd = stupwd == null ? null : stupwd.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.stuStust
     *
     * @return the value of student.stuStust
     *
     * @mbg.generated
     */
    public String getStustust() {
        return stustust;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.stuStust
     *
     * @param stustust the value for student.stuStust
     *
     * @mbg.generated
     */
    public void setStustust(String stustust) {
        this.stustust = stustust == null ? null : stustust.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.stuSta
     *
     * @return the value of student.stuSta
     *
     * @mbg.generated
     */
    public Integer getStusta() {
        return stusta;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.stuSta
     *
     * @param stusta the value for student.stuSta
     *
     * @mbg.generated
     */
    public void setStusta(Integer stusta) {
        this.stusta = stusta;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.stuStartDate
     *
     * @return the value of student.stuStartDate
     *
     * @mbg.generated
     */
    public Date getStustartdate() {
        return stustartdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.stuStartDate
     *
     * @param stustartdate the value for student.stuStartDate
     *
     * @mbg.generated
     */
    public void setStustartdate(Date stustartdate) {
        this.stustartdate = stustartdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.stuEndDate
     *
     * @return the value of student.stuEndDate
     *
     * @mbg.generated
     */
    public Date getStuenddate() {
        return stuenddate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.stuEndDate
     *
     * @param stuenddate the value for student.stuEndDate
     *
     * @mbg.generated
     */
    public void setStuenddate(Date stuenddate) {
        this.stuenddate = stuenddate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.teaId
     *
     * @return the value of student.teaId
     *
     * @mbg.generated
     */
    public Integer getTeaid() {
        return teaid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.teaId
     *
     * @param teaid the value for student.teaId
     *
     * @mbg.generated
     */
    public void setTeaid(Integer teaid) {
        this.teaid = teaid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.stuBirth
     *
     * @return the value of student.stuBirth
     *
     * @mbg.generated
     */
    public Date getStubirth() {
        return stubirth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.stuBirth
     *
     * @param stubirth the value for student.stuBirth
     *
     * @mbg.generated
     */
    public void setStubirth(Date stubirth) {
        this.stubirth = stubirth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.stuSex
     *
     * @return the value of student.stuSex
     *
     * @mbg.generated
     */
    public Integer getStusex() {
        return stusex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.stuSex
     *
     * @param stusex the value for student.stuSex
     *
     * @mbg.generated
     */
    public void setStusex(Integer stusex) {
        this.stusex = stusex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.stuImg
     *
     * @return the value of student.stuImg
     *
     * @mbg.generated
     */
    public String getStuimg() {
        return stuimg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.stuImg
     *
     * @param stuimg the value for student.stuImg
     *
     * @mbg.generated
     */
    public void setStuimg(String stuimg) {
        this.stuimg = stuimg == null ? null : stuimg.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.extend1
     *
     * @return the value of student.extend1
     *
     * @mbg.generated
     */
    public String getExtend1() {
        return extend1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.extend1
     *
     * @param extend1 the value for student.extend1
     *
     * @mbg.generated
     */
    public void setExtend1(String extend1) {
        this.extend1 = extend1 == null ? null : extend1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.extend2
     *
     * @return the value of student.extend2
     *
     * @mbg.generated
     */
    public String getExtend2() {
        return extend2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.extend2
     *
     * @param extend2 the value for student.extend2
     *
     * @mbg.generated
     */
    public void setExtend2(String extend2) {
        this.extend2 = extend2 == null ? null : extend2.trim();
    }
}