package com.singulee.carschool.pojo;

import java.util.Date;

public class Teacher{
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column teacher.teaId
     *
     * @mbg.generated
     */
    private Integer teaid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column teacher.teaName
     *
     * @mbg.generated
     */
    private String teaname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column teacher.teaPhone
     *
     * @mbg.generated
     */
    private String teaphone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column teacher.teaPwd
     *
     * @mbg.generated
     */
    private String teapwd;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column teacher.teaSex
     *
     * @mbg.generated
     */
    private String teasex;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column teacher.teaSta
     *
     * @mbg.generated
     */
    private String teasta;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column teacher.teaRole
     *
     * @mbg.generated
     */
    private Integer tearole;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column teacher.teaDriver
     *
     * @mbg.generated
     */
    private Integer teadriver;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column teacher.teaStartDate
     *
     * @mbg.generated
     */
    private Date teastartdate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column teacher.teaEndDate
     *
     * @mbg.generated
     */
    private Date teaenddate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column teacher.teaBirth
     *
     * @mbg.generated
     */
    private Date teabirth;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column teacher.teaDescript
     *
     * @mbg.generated
     */
    private String teadescript;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column teacher.teaImg
     *
     * @mbg.generated
     */
    private String teaimg;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column teacher.extend1
     *
     * @mbg.generated
     */
    private String extend1;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column teacher.exten2
     *
     * @mbg.generated
     */
    private String exten2;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column teacher.teaId
     *
     * @return the value of teacher.teaId
     *
     * @mbg.generated
     */
    public Integer getTeaid() {
        return teaid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column teacher.teaId
     *
     * @param teaid the value for teacher.teaId
     *
     * @mbg.generated
     */
    public void setTeaid(Integer teaid) {
        this.teaid = teaid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column teacher.teaName
     *
     * @return the value of teacher.teaName
     *
     * @mbg.generated
     */
    public String getTeaname() {
        return teaname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column teacher.teaName
     *
     * @param teaname the value for teacher.teaName
     *
     * @mbg.generated
     */
    public void setTeaname(String teaname) {
        this.teaname = teaname == null ? null : teaname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column teacher.teaPhone
     *
     * @return the value of teacher.teaPhone
     *
     * @mbg.generated
     */
    public String getTeaphone() {
        return teaphone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column teacher.teaPhone
     *
     * @param teaphone the value for teacher.teaPhone
     *
     * @mbg.generated
     */
    public void setTeaphone(String teaphone) {
        this.teaphone = teaphone == null ? null : teaphone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column teacher.teaPwd
     *
     * @return the value of teacher.teaPwd
     *
     * @mbg.generated
     */
    public String getTeapwd() {
        return teapwd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column teacher.teaPwd
     *
     * @param teapwd the value for teacher.teaPwd
     *
     * @mbg.generated
     */
    public void setTeapwd(String teapwd) {
        this.teapwd = teapwd == null ? null : teapwd.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column teacher.teaSex
     *
     * @return the value of teacher.teaSex
     *
     * @mbg.generated
     */
    public String getTeasex() {
        return teasex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column teacher.teaSex
     *
     * @param teasex the value for teacher.teaSex
     *
     * @mbg.generated
     */
    public void setTeasex(String teasex) {
        this.teasex = teasex == null ? null : teasex.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column teacher.teaSta
     *
     * @return the value of teacher.teaSta
     *
     * @mbg.generated
     */
    public String getTeasta() {
        return teasta;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column teacher.teaSta
     *
     * @param teasta the value for teacher.teaSta
     *
     * @mbg.generated
     */
    public void setTeasta(String teasta) {
        this.teasta = teasta == null ? null : teasta.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column teacher.teaRole
     *
     * @return the value of teacher.teaRole
     *
     * @mbg.generated
     */
    public Integer getTearole() {
        return tearole;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column teacher.teaRole
     *
     * @param tearole the value for teacher.teaRole
     *
     * @mbg.generated
     */
    public void setTearole(Integer tearole) {
        this.tearole = tearole;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column teacher.teaDriver
     *
     * @return the value of teacher.teaDriver
     *
     * @mbg.generated
     */
    public Integer getTeadriver() {
        return teadriver;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column teacher.teaDriver
     *
     * @param teadriver the value for teacher.teaDriver
     *
     * @mbg.generated
     */
    public void setTeadriver(Integer teadriver) {
        this.teadriver=teadriver;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column teacher.teaStartDate
     *
     * @return the value of teacher.teaStartDate
     *
     * @mbg.generated
     */
    public Date getTeastartdate() {
        return teastartdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column teacher.teaStartDate
     *
     * @param teastartdate the value for teacher.teaStartDate
     *
     * @mbg.generated
     */
    public void setTeastartdate(Date teastartdate) {
        this.teastartdate = teastartdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column teacher.teaEndDate
     *
     * @return the value of teacher.teaEndDate
     *
     * @mbg.generated
     */
    public Date getTeaenddate() {
        return teaenddate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column teacher.teaEndDate
     *
     * @param teaenddate the value for teacher.teaEndDate
     *
     * @mbg.generated
     */
    public void setTeaenddate(Date teaenddate) {
        this.teaenddate = teaenddate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column teacher.teaBirth
     *
     * @return the value of teacher.teaBirth
     *
     * @mbg.generated
     */
    public Date getTeabirth() {
        return teabirth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column teacher.teaBirth
     *
     * @param teabirth the value for teacher.teaBirth
     *
     * @mbg.generated
     */
    public void setTeabirth(Date teabirth) {
        this.teabirth = teabirth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column teacher.teaDescript
     *
     * @return the value of teacher.teaDescript
     *
     * @mbg.generated
     */
    public String getTeadescript() {
        return teadescript;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column teacher.teaDescript
     *
     * @param teadescript the value for teacher.teaDescript
     *
     * @mbg.generated
     */
    public void setTeadescript(String teadescript) {
        this.teadescript = teadescript == null ? null : teadescript.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column teacher.teaImg
     *
     * @return the value of teacher.teaImg
     *
     * @mbg.generated
     */
    public String getTeaimg() {
        return teaimg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column teacher.teaImg
     *
     * @param teaimg the value for teacher.teaImg
     *
     * @mbg.generated
     */
    public void setTeaimg(String teaimg) {
        this.teaimg = teaimg == null ? null : teaimg.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column teacher.extend1
     *
     * @return the value of teacher.extend1
     *
     * @mbg.generated
     */
    public String getExtend1() {
        return extend1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column teacher.extend1
     *
     * @param extend1 the value for teacher.extend1
     *
     * @mbg.generated
     */
    public void setExtend1(String extend1) {
        this.extend1 = extend1 == null ? null : extend1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column teacher.exten2
     *
     * @return the value of teacher.exten2
     *
     * @mbg.generated
     */
    public String getExten2() {
        return exten2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column teacher.exten2
     *
     * @param exten2 the value for teacher.exten2
     *
     * @mbg.generated
     */
    public void setExten2(String exten2) {
        this.exten2 = exten2 == null ? null : exten2.trim();
    }

    @Override
    public String toString() {
        return "Teacher{" +
                "teaid=" + teaid +
                ", teaname='" + teaname + '\'' +
                ", teaphone='" + teaphone + '\'' +
                ", teapwd='" + teapwd + '\'' +
                ", teasex='" + teasex + '\'' +
                ", teasta='" + teasta + '\'' +
                ", tearole=" + tearole +
                ", teadriver=" + teadriver +
                ", teastartdate=" + teastartdate +
                ", teaenddate=" + teaenddate +
                ", teabirth=" + teabirth +
                ", teadescript='" + teadescript + '\'' +
                ", teaimg='" + teaimg + '\'' +
                ", extend1='" + extend1 + '\'' +
                ", exten2='" + exten2 + '\'' +
                '}';
    }
}